name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # begin-snippet: simple-build
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
      # end-snippet: simple-build

      - run: dotnet build
        working-directory: simple/app

  globaljson-not-used:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # begin-snippet: globaljson-not-used-build
      - uses: actions/setup-dotnet@v6
      # end-snippet: globaljson-not-used-build

      - run: dotnet build
        working-directory: globaljson/tests

      - run: dotnet test
        working-directory: globaljson/tests

  globaljson:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # begin-snippet: globaljson-build
      - uses: actions/setup-dotnet@v6
        with:
          global-json-file: globaljson/global.json
      # end-snippet: globaljson-build

      - run: dotnet build
        working-directory: globaljson/tests

      - run: dotnet test
        working-directory: globaljson/tests

  globaljson-and-nugetconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # begin-snippet: globaljson-and-nugetconfig-build
      - uses: actions/setup-dotnet@v6
        with:
          global-json-file: globaljson-and-nugetconfig/global.json
          source-url: https://nuget.pkg.github.com/flcdrg/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # end-snippet: globaljson-and-nugetconfig-build

      - run: dotnet build
        working-directory: globaljson-and-nugetconfig/tests

      - run: dotnet test
        working-directory: globaljson-and-nugetconfig/tests

  globaljson-and-nugetconfig-configfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # begin-snippet: globaljson-and-nugetconfig-configfile-build
      - uses: actions/setup-dotnet@v6
        with:
          global-json-file: globaljson-and-nugetconfig/global.json
          source-url: https://nuget.pkg.github.com/flcdrg/index.json
          config-file: globaljson-and-nugetconfig/nuget.config
      # end-snippet: globaljson-and-nugetconfig-configfile-build

        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: dotnet build
        working-directory: globaljson-and-nugetconfig/tests

      - run: dotnet test
        working-directory: globaljson-and-nugetconfig/tests

  globaljson-and-nugetconfig-clear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # begin-snippet: globaljson-and-nugetconfig-clear-build
      - uses: actions/setup-dotnet@v6
        with:
          global-json-file: globaljson-and-nugetconfig-clear/global.json
          source-url: https://nuget.pkg.github.com/flcdrg/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # end-snippet: globaljson-and-nugetconfig-clear-build

      - run: dotnet build
        working-directory: globaljson-and-nugetconfig-clear/tests

      - run: dotnet test
        working-directory: globaljson-and-nugetconfig-clear/tests
